head(Sleep$Age)
head(Sleep)
plot(Sleep$Age, Sleep$`Quality of Sleep`)
pine.lm <- lm(`Quality of Sleep` ~ Age, data = Sleep)
lm(`Quality of Sleep` ~ Age, data = Sleep)
pine.lm
abline(pine.lm, col = "blue")
coef(pine.lm)
predict(pine.lm, newdata = data.frame(Age = 35))
predict(pine.lm, newdata = data.frame(Age = c(40, 45, 50)))
plot(Sleep$Age,Sleep$`Quality of Sleep`, xlab = "Age", ylab = "Quality of Sleep", main = "Sleep Data")
cor(Sleep$`Quality of Sleep`, Sleep$Age)
model <- lm(`Quality of Sleep` ~ Age, data = Sleep)
summary(model)
summary(model)$r.squared
x <- c(Sleep$Age)
y <- c(Sleep$`Quality of Sleep`)
cor.test(x,y)
cor.test(x,y)$p.value
x <- rnorm(n=100, Sleep$Age)
y <- rnorm(100, Sleep$`Quality of Sleep`)
data <- data.frame(x, y)
head(data)
model <- lm(y ~ x, data=data)
library(ggplot2)
library(ggplot2)
ggplot(data = data, aes( x = model$residuals)) + geom_histogram(fill = "steelblue", color ="black") + labs(title = "Histogram of Residuals", x = "Residuals", y = "Frecuency")
model <- lm(`Quality of Sleep` ~ Age, data = Sleep)
res <- resid(model)
plot(fitted(model), res)
abline(0,0)
qqnorm(res)
qqline(res)
