Sleep <- read_csv("Sleep_health_and_lifestyle_dataset.csv")
View(Sleep)
data <- c(sleep)
xbar <- sd(data)
xbar <- sd(sleep)
data <- c(sleep)
xbar <- mean(sleep)
data <- c(sleep$Age)
xbar <- mean(sleep$Age)
data <- c(Sleep$Age)
xbar <- mean(Sleep$Age)
mean(Sleep$Age)
sd(Sleep$Age)
n <- 374
qt(0.95,374-1)
t <- qt(0.95,374-1)
s <- sd(Sleep$Age)
L <- xbar - t*s/sqrt(n)
xbar - t*s/sqrt(n)
U = xbar + t*s/sqrt(n)
xbar + t*s/sqrt(n)
t <- -qt(0.025,374-1)
-qt(0.025,374-1)

data <- c(Sleep$`Person ID`)
xbar <- sd(Sleep$`Person ID`)
sd(Sleep$`Person ID`)
mean(Sleep$`Person ID`)
n <- 374
t <- qt(0.95, 374-1)
qt(0.95,374-1)
s <- sd(Sleep$`Person ID`)
L <- xbar - t*s/sqrt(n)
xbar - t*s/sqrt(n)
U = xbar + t*s/sqrt(n)
xbar +t*s/sqrt(n)
t <- -qt(0.025, 374-1)
-qt(0.025,374-1)
